//
//  DataModels.h
//
//  Created by   on 2017/6/6
//  Copyright (c) 2017 __MyCompanyName__. All rights reserved.
//

#import "CodeIsBaseClass.h"
#import "LoginsIsBaseClass.h"
#import "BasicInformationInfo.h"
#import "BasicInformationBaseClass.h"
#import "MyMessageListBaseClass.h"
#import "MyMessageListResultList.h"
#import "MyMessageListData.h"
#import "WalletBalanceBaseClass.h"
#import "Top_up_detailBaseClass.h"
#import "Top_up_detailResultList.h"
#import "Top_up_detailPagingList.h"
#import "StatementBaseClass.h"
#import "StatementResultList.h"
#import "StatementPagingList.h"
#import "AnnouncementListBaseClass.h"
#import "AnnouncementListResultList.h"
#import "AnnouncementListData.h"
#import "CouponsListBaseClass.h"
#import "CouponsListResultList.h"
#import "CouponsListPagingList.h"
#import "MonthsThanksGoodsBaseClass.h"
#import "MonthsThanksGoodsResultList.h"
#import "MonthsThanksGoodsPagingList.h"
#import "GoodsDetilComm.h"
#import "GoodsDetilListComment.h"
#import "GoodsDetilBaseClass.h"
#import "EvaluationListBaseClass.h"
#import "EvaluationListResultList.h"
#import "EvaluationListListComment.h"
#import "NearTheEquipmentEquipment.h"
#import "NearTheEquipmentBaseClass.h"
#import "VIPBaseClass.h"
#import "VIPResultList.h"
#import "VIPPagingList.h"
#import "VIPRecordsBaseClass.h"
#import "VIPRecordsResultList.h"
#import "VIPRecordsPagingList.h"
#import "OrderBaseClass.h"
#import "OrderResultList.h"
#import "OrderPagingList.h"
#import "EquipmentCommodityBaseClass.h"
#import "EquipmentCommodityResultList.h"
#import "EquipmentCommodityPagingList.h"
#import "CouponList.h"
#import "BaseClass.h"


